// Mewstats
//
// Copyright (C) 2026  Mee;w
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#if defined _mewstats_classname_included_
#endinput
#endif
#define _mewstats_classname_included_

#define MEWSTATS_CLASSNAME_WEAPON_FLASHBANG "weapon_flashbang"
#define MEWSTATS_CLASSNAME_PROJECTILE_FLASHBANG "flashbang_projectile"
#define MEWSTATS_CLASSNAME_SIZE 128
