// Mewstats
//
// Copyright (C) 2026  Mee;w
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#if defined _mewstats_info_included_
#endinput
#endif
#define _mewstats_info_included_

#include <mewstats/version>

#define MEWSTATS_NAME "Mewstats"
#define MEWSTATS_NAME_LOWER "mewstats"
#define MEWSTATS_AUTHOR "Mee;w"
#define MEWSTATS_DESCRIPTION "Various boost stats for Trikz"
#define MEWSTATS_URL "https://github.com/herbary/mewstats"

#define MEWSTATS_VERSION MEWSTATS_VERSION_IMPL(MEWSTATS_VERSION_MAJOR_STRING, MEWSTATS_VERSION_MINOR_STRING, MEWSTATS_VERSION_PATCH_STRING)
