#if defined _mewstats_info_included_
#endinput
#endif
#define _mewstats_info_included_

#include <mewstats/version>

#define MEWSTATS_NAME "Mewstats"
#define MEWSTATS_NAME_LOWER "mewstats"
#define MEWSTATS_AUTHOR "Mee;w"
#define MEWSTATS_DESCRIPTION "Various boost stats for Trikz"
#define MEWSTATS_URL "https://github.com/herbary/mewstats"

#define MEWSTATS_VERSION MEWSTATS_VERSION_IMPL(MEWSTATS_VERSION_MAJOR_STRING, MEWSTATS_VERSION_MINOR_STRING, MEWSTATS_VERSION_PATCH_STRING)
