#if defined _mewstats_prop_included_
#endinput
#endif
#define _mewstats_prop_included_

#define MEWSTATS_PROP_M_HTHROWER "m_hThrower"
#define MEWSTATS_PROP_M_VECABSVELOCITY "m_vecAbsVelocity"
#define MEWSTATS_PROP_M_VECORIGIN "m_vecOrigin"
#define MEWSTATS_PROP_M_VECMAXS "m_vecMaxs"
#define MEWSTATS_PROP_M_NTICKBASE "m_nTickBase"
#define MEWSTATS_PROP_M_FFLAGS "m_fFlags"
#define MEWSTATS_PROP_M_BDUCKED "m_bDucked"
#define MEWSTATS_PROP_M_IOBSERVERMODE "m_iObserverMode"
#define MEWSTATS_PROP_M_HOBSERVERTARGET "m_hObserverTarget"
