// Mewstats
//
// Copyright (C) 2026  Mee;w
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#if defined _mewstats_prop_included_
#endinput
#endif
#define _mewstats_prop_included_

#define MEWSTATS_PROP_M_HTHROWER "m_hThrower"
#define MEWSTATS_PROP_M_VECABSVELOCITY "m_vecAbsVelocity"
#define MEWSTATS_PROP_M_VECORIGIN "m_vecOrigin"
#define MEWSTATS_PROP_M_VECMAXS "m_vecMaxs"
#define MEWSTATS_PROP_M_NTICKBASE "m_nTickBase"
#define MEWSTATS_PROP_M_FFLAGS "m_fFlags"
#define MEWSTATS_PROP_M_BDUCKED "m_bDucked"
#define MEWSTATS_PROP_M_IOBSERVERMODE "m_iObserverMode"
#define MEWSTATS_PROP_M_HOBSERVERTARGET "m_hObserverTarget"
